FROM python:3.12

WORKDIR /app

COPY docker/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY train/ ./train/

CMD ["uvicorn", "api.clustering_api:app", "--host", "0.0.0.0", "--port", "8005"]